spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: test
#application name register with eureka
  application:
    name: coupon-service-v1
#client will register with eureka
eureka:
  client:
    service-url.defaultZone: http://localhost:8761/eureka/

server:
  port: 8085
